services:
  coturn:
    image: <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/coturn-turn-server:latest
    restart: unless-stopped
    network_mode: host
    environment:
      TURN_SHARED_SECRET: "${TURN_SHARED_SECRET}"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
